//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplicationSysTech1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfApplicationSysTech1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не найден файл appsettings.json.
        /// </summary>
        internal static string AppSettigsFileNotFoundText {
            get {
                return ResourceManager.GetString("AppSettigsFileNotFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка авторизации.
        /// </summary>
        internal static string AuthErrorText {
            get {
                return ResourceManager.GetString("AuthErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не найден файл базы данных.
        /// </summary>
        internal static string DbFileNotFoundText {
            get {
                return ResourceManager.GetString("DbFileNotFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загружаем список позиций.
        /// </summary>
        internal static string LoadingPositionsArrText {
            get {
                return ResourceManager.GetString("LoadingPositionsArrText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успешная авторизация.
        /// </summary>
        internal static string SuccessAuthText {
            get {
                return ResourceManager.GetString("SuccessAuthText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбранный объект не является объектом типа UserListItem.
        /// </summary>
        internal static string ThisIsNotUserListItemText {
            get {
                return ResourceManager.GetString("ThisIsNotUserListItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При создании UserListItem произошла ошибка (массив позиций пуст).
        /// </summary>
        internal static string UserListItemCreationErrorText {
            get {
                return ResourceManager.GetString("UserListItemCreationErrorText", resourceCulture);
            }
        }
    }
}
